# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "Lucky-Light-Sun"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 15

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
# `au:del_maestro AND ti:checkerboard`
# ! prefix explanation !
# ti: Title, au: Author, abs: Abstract, co: Comment, jr: Journal Reference, cat: Subject Category
# rn: Report Number, id: Id (use id_list instead), all: All of the above
# AND | OR | ANDNOT, ( ), ""

# https://info.arxiv.org/help/api/user-manual.html#query_details
keywords:
    "diffusion model": 
        filters: [
            "abs:diffusion AND 
            all:('Google Research' OR 'Google Deepmind' 
                  OR '@OpenAI.com' 
                  OR 'Microsoft Research' OR '@microsoft.com' 
                  OR 'Meta AI' OR '@fb.com' 
                  OR 'University of California, Berkeley' 
                  OR 'Stanford University')"
        ]
    "diffusion-segmentation":
        filters: ["abs:'diffusion segmentation'"]
    "medical segmentation":
        filters: ["abs:'medical segmentation'"]
    "semantic segmentation":
        filters: ["abs:'semantic segmentation'"]
    "fine-tune":
        filters: ["fine-tuning"]
